apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rs
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
      environment: dev
  template:
    metadata:
      labels:
        app: nginx-demo
        environment: dev
    spec:
      containers:
        - name: nginx-demo
          image: nginx
          ports:
            - containerPort: 80